language: go

go:
  - 1.5.1

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - pwd
  - ls -lah
  - goveralls -package=./internal/task/ -service=travis-ci
  - cd ./internal/task
  - goveralls -service=travis-ci
