language: go

go:
  - 1.5.1

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

script:
  - pwd
  - goveralls
  #- $HOME/gopath/bin/goveralls -package=$TRAVIS_BUILD/internal/task/ -service=travis-ci
